### ISSUE TITLE
feat: prepare a way to manage confidential information

### ISSUE THREAD

**Issue by yktt-nuane** [yktt-nuane/shiftmaking#11]
### Goal

Confidential information can be shared in Git with authorized developers.

### Acceptance criteria

- [ ] A command is provided to encrypt information that you want to keep secret
- [ ] Secret information is securely shared in Git
- [ ] A command is provided to decrypt information for authorized developers only

### Proposal

- [git-secret](https://git-secret.io)
- [git-crypt](https://github.com/AGWA/git-crypt)
- [AWS KMS](https://aws.amazon.com/jp/kms/)
- [GCP CKM](https://cloud.google.com/security-key-management)
- [Hashicorp Vault](https://www.vaultproject.io)
- [1Password CLI](https://1password.com/jp/developers/)

### Appendix

None

**Comment by shin-sforzando** [comment]
> all 1 files are revealed.
1なら単数形では。

**Comment by yktt-nuane** [comment]
> > all 1 files are revealed.
> 
> 1なら単数形では。そして、英語は先頭文字、大文字です。

![image](https://user-images.githubusercontent.com/61369434/207209699-f908edae-0be0-4349-8ec9-5c12f1017bb7.png)
こんな感じで表示されますが、正しい英語にすべきですか？

**Comment by shin-sforzando** [comment]
これ、git-secretの出力なんですね？
じゃ、そう分かるように書かないと英作文能力疑われますよ。

```shell
$ git secret reveal
git-secret: done. 1 of 1 files are revealed.
```

**Comment by shin-sforzando** [comment]
てか、ACの考え方間違ってるな。
git-secretを使うかさておき、それがどんな出力をするかじゃないですよね。
やりたいのは暗号/復号であって画面出力を得たいわけじゃない。（それなら、そういうprint文のプログラムを実装したって正解って事になる）
大事なのは手元のファイルがちゃんと暗号化/復号されてるか、じゃないですか？

**Comment by shin-sforzando** [comment]
いや、全然わかってない。ACは手順じゃないんですって。続きはSlackで。

**Comment by yktt-nuane** [comment]
Slack拝見致しました。理解致しました。どうでしょうか？

**Comment by shin-sforzando** [comment]
Goal、"Confidential information can be shared by multiple people." multiple peoleじゃなくて「限られた人」「権限を持つ人」的な記述じゃなきゃダメですね。

**Comment by shin-sforzando** [comment]
Proposalがおかしくて、ここも手順じゃないです。
秘匿情報を扱うために使えそうなもの、たとえばgit-secretでもいいし、AWS KMSでもいいし1Passwordでもいいし、Vaultでもいい、そういうことを書く章です。実際にどれを使うかは専門家が決めます。
素人が「私は〜って病気のはずなんで手術しかないです、Aって薬を使って、Bの手術をしてください」とか言ってるの、変でしょ。

**Comment by shin-sforzando** [comment]
だからProposalはOptionalです。書いてなくても良いです。

**Comment by yktt-nuane** [comment]
これで、どうでしょうか？
