### ISSUE TITLE
feat: introduce linters

### ISSUE THREAD

**Issue by yktt-nuane** [yktt-nuane/shiftmaking#2]
### Goal

開発環境が完成する。
Prettier + Stylelint + ESLint が導入されて、フォーマットチェックがされる状態。
Gitコミット時に必ず整形された状態を保つようにする。
VSCodeのプラグインも準備してsettings.json extensions.json が機能する。

### Acceptance criteria

 `npm run format`
- [ ] 種々のLInterらが正常に終了し、全てのファイルが整形されている。
- [ ] VSCodeで編集すると、保存するだけでフォーマットされる。

### Proposal

- VSCodeのプラグイン

**Comment by shin-sforzando** [comment]
2022/12/08現在、一番最初に着手するIssueがこれだと思うので、これのAcceptance Criteriaだけでも明記しちゃってください。

**Comment by yktt-nuane** [comment]
他のissueと見比べて、コードのフォーマットかなと思ったのですが、合ってますでしょうか？
...Acceptance Criteriaが、めちゃくちゃ難しいのですが、こんな感じでしょうか？

**Comment by shin-sforzando** [comment]
「開発環境の構築」と言った場合、まっさらな状態の新人がこのレポジトリをcloneして「さぁ、どうするの？」という状態を救う手順をREADME.mdに記載すべきですね。

それを踏まえ、その手順の中でLinterの導入および強制は確かに最初期に行いたいタスクなのですが、
であるならば、このIssueは"feat: introduce linters"とかの方が適切でしょうね。
で、Linterの導入ならばHuskyないしはprecommitないしはLefthook等を使って、Gitコミット時に必ず整形された状態を保つようにするまでをスコープにしましょう。
かつ、昨今であればVSCodeで開発すると思われますから、 `settings.json` `extensions.json` も用意して、保存するだけでフォーマットされる、まで強制してしまいましょう。

**Comment by shin-sforzando** [comment]
Acceptance Criteria（以下、AC）について、繰り返しになりますが「ゴールが達成されたかを外部の人間がどうやって確認するか？」なので、
今の記述だと足りなくて、
「 `npm run format` を実行したら、種々のLInterらが正常に終了し、〜のファイルが全て整形されている」とかでしょうか。

**Comment by shin-sforzando** [comment]
ちなみに、Proposalに書いてある「VS.code」ですが、これもタイポですね。
正式な略称は「VSCode」と思います。
https://ja.wikipedia.org/wiki/Visual_Studio_Code

**Comment by yktt-nuane** [comment]
Huskyを使って、Git commit時に整形される状態を目指します。
ご指摘の修正をしてみました。
手をつけ始めて良いでしょうか？

**Comment by shin-sforzando** [comment]
時間がないので #2 は着手しましょう。
かつ、他のIssueのAC埋めて、関係性を俯瞰し、細かな達成条件の集合がv1.0の達成になってるか確認しましょう。

**Comment by yktt-nuane** [comment]
承知致しました。#2 着手します。
