### ISSUE TITLE
feat: prepare unit test framework

### ISSUE THREAD

**Issue by yktt-nuane** [yktt-nuane/shiftmaking#5]
### Goal

Automated unit tests are performed at pre-push.

### Acceptance criteria

- Able to run unit tests.
- Unit tests are automatically run before pushing to GitHub.
- Test coverage can be measured.

### Proposal

- [Vitest](https://vitest.dev/)
- [Jest](https://jestjs.io/ja/)

### Appendix

- [Testing | Next.js](https://nextjs.org/docs/testing)
- https://github.com/vercel/next.js/tree/canary/examples/with-vitest
- Test coverage target is 50%.

**Comment by shin-sforzando** [comment]
ゴールは「自動テストができる状態」、もっと厳密にいうと「自動ユニットテストが行われる状態」ですね。
ちなみに、E2Eテストはどうしますか？

**Comment by yktt-nuane** [comment]
「自動ユニットテストが行われる状態」に変更しました。
E2Eテストは入れたいです。
（見た目のテスト・結合テストであるという認識のみで、まだ具体的には何も知りませんが…）

**Comment by shin-sforzando** [comment]
入れたいならIssueにしておきましょう。

**Comment by yktt-nuane** [comment]
issueに追加しました。

**Comment by shin-sforzando** [comment]
> npm run test and then run jest.

だからぁ、ACに具体的なライブラリ名が入ってるのおかしいですって。
専門家が見たらJestより良い選択肢いっぱいあるかもしれないじゃないですか。

**Comment by yktt-nuane** [comment]
1週間以上前に書いたままなので、まずは中身を修正します。

**Comment by yktt-nuane** [comment]
issue修正しました。取り掛かって良いでしょうか？

**Comment by shin-sforzando** [comment]
Typo、正しくは"GitHub"です。

また、ユニットテストはカバレッジを測らないとすぐ形骸化してしまうので本Issueで導入した方が良いと思います。
ライブラリ1,2個追加で入れるだけなので難しくはないです。
問題は、今後テストカバレッジを何%維持する目標にするか、ですが。

**Comment by yktt-nuane** [comment]
テストカバレッジを計測するも追加しました。
達成目標の設定もこのissueに含まれますか？
数字に関しては皆目見当が付かないです。

**Comment by shin-sforzando** [comment]
良いACと思います。
テストカバレッジはシステムの性質によって限りなく100％に近づけなければいけないプロジェクトもあれば、50％で良いものもあります。
shiftmakingは、まず50％を目安にしてはいかがでしょうか。
