### ISSUE TITLE
feat: prepare logging tools

### ISSUE THREAD

**Issue by yktt-nuane** [yktt-nuane/shiftmaking#7]
### Goal

prepared logging tool.

### Acceptance criteria

- [ ] Logs can be checked in the same time lines.

### Proposal

- [Axiom](https://www.axiom.co/)
- [Logflare](https://logflare.app/)

### Appendix

None

**Comment by shin-sforzando** [comment]
生成するわけではないですね。公式Docで言うところの https://nextjs.org/docs/going-to-production#logging こう言うことです。

**Comment by yktt-nuane** [comment]
「ログが確認できる状態」という事ですか？

**Comment by shin-sforzando** [comment]
公式Docでも説明されているんですが、Next.jsの場合、サーバー側で発生した事象はサーバー側に出力され、クライアント(= ブラウザ)側の事象はクライアント側に出力されます。
例えば、「ログインがうまくいかない」ってトラブルが起きたとして、開発者は両方のログを同じ時系列で見れないと原因究明しにくいですよね。それを可能にする状態、ってことです。
